### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by MatthewDawn** [ImproveWebsite/website#1]
Ben zeer moe maar heb even mijn mockups wat aangepast. Denk dat deze goed werkbaar zijn voor een eerste versie, niet moeilijk, clean maar toch niet lelijk.

Ik denk dat impro.ve een goeie domeinnaam is voorlopig? (ve  = venezuela)

Zal de aparte assets later uploaden.

![improve_image-page](https://cloud.githubusercontent.com/assets/12302152/7576920/27109d72-f843-11e4-9e4d-1bd393b55520.jpg)
![improve_landing-page](https://cloud.githubusercontent.com/assets/12302152/7576921/27120f22-f843-11e4-8b70-f2cb8a6214c6.jpg)

**Comment by nicolaspierre1990** [comment]
Ziet er nice uit. Ik begin meteen aan het design te implementeren

**Comment by nicolaspierre1990** [comment]
ART dropdown menu (pool wisselen).
